name: CI Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: docker-compose build
        run: docker-compose build --no-cache

      - name: Run tests
        run: docker-compose run web htmlproofer docs/_site
    