name: CI Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and test in Docker container 
        uses: ./.github/actions/jekyll